name: RSS to Discord

on:
  schedule:
    # 毎時実行
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  check-rss:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build TypeScript
        run: npm run build

      - name: Cache RSS check data
        uses: actions/cache@v4
        with:
          path: last_check.json
          key: rss-cache-${{ github.sha }}
          restore-keys: |
            rss-cache-

      - name: Run RSS check
        env:
          DISCORD_CONFERENCE_WEBHOOK_URL: ${{ secrets.DISCORD_CONFERENCE_WEBHOOK_URL }}
          DISCORD_INFORMATION_WEBHOOK_URL: ${{ secrets.DISCORD_INFORMATION_WEBHOOK_URL }}
        run: npm start
